I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/main_room.rpy", line 61, in script call
    call auditorium from _call_auditorium
  File "game/main_room.rpy", line 65, in script call
    call dining_hall from _call_dining_hall
  File "game/main_room.rpy", line 69, in script call
    call launch_deck from _call_launch_deck
  File "game/nav_bridge.rpy", line 49, in script
    c "This is the SERAPHIM. We are reporting an ongoing incident on board."
Exception: Sayer b'c' is not a function or string.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/main_room.rpy", line 61, in script call
    call auditorium from _call_auditorium
  File "game/main_room.rpy", line 65, in script call
    call dining_hall from _call_dining_hall
  File "game/main_room.rpy", line 69, in script call
    call launch_deck from _call_launch_deck
  File "game/nav_bridge.rpy", line 49, in script
    c "This is the SERAPHIM. We are reporting an ongoing incident on board."
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 898, in execute
    raise Exception("Sayer %s is not a function or string." % self.who.encode("utf-8"))
Exception: Sayer b'c' is not a function or string.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
BABEL 1.0
Tue Apr  4 12:44:48 2023
